# Change these first
owner: rtvapeldoorn # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Website RTV Apeldoorn
    url: https://www.rtv-apeldoorn.nl
  - name: Streaming Radio RTV Apeldoorn
    url: https://streamingradio.rtv-apeldoorn.nl/login
  - name: YouTube kanaal RTV Apeldoorn
    url: https://www.youtube.com/@rtvapeldoorn/videos
  - name: RTV Apeldoorn Ticketsysteem
    url: https://storing.rtv-apeldoorn.nl/
  - name: RTV Apeldoorn locatiestream
    url: http://95.97.176.18:4000/status.xsl
#  - name: IPv6 test
#    url: forwardemail.net
#    port: 80
#    check: "tcp-ping"
#    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.rtv-apeldoorn.nl
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: RTV Apeldoorn services
  introTitle: "Uptime RTV Apeldoorn services"
  introMessage: Deze pagina geeft de actuele status van onze diensten weer.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
